version: "3.9"
networks:
  asa-bridge:
    ipam:
      config:
        - subnet: 10.18.0.0/16

services:
  projeto_asa:
    build: ./projeto/.
    ports:
      - "8000:8000"
    networks:
      asa-bridge:
        ipv4_address: 10.18.0.10
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=trabalhoasa
      - POSTGRES_PASSWORD=Asa2024!
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      asa-bridge:
        ipv4_address: 10.18.0.20

